### ISSUE TITLE
Library includes in the RGB examples are wrong

### ISSUE THREAD

**Issue by Antrilas** [arduino-libraries/Arduino_GigaDisplay#8]
The two examples in "Examples->Arduino_GigaDisplay->Blink->*" have the following includes:

`#include <Arduino_GigaDisplayRGB.h>`

Compiling leads to:
`Compilation error: Arduino_GigaDisplayRGB.h: No such file or directory`

To fix this change the include to:

`#include <Arduino_GigaDisplay.h>`

**Comment by karlsoderby** [comment]
Hi @Antrilas , thanks for highlighting this issue. It has been addressed in this PR: https://github.com/arduino-libraries/Arduino_GigaDisplay/pull/10

**Comment by Antrilas** [comment]
@karlsoderby thank you, your fix went wrong though :)
You forgot the #include
